### ISSUE TITLE
Infografia Josue Angel

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/infografia-de-hilos-22620229Angel#2]
[Infografia Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-22620229Angel/files/15118905/Infografia.Hilos.pdf)

**Comment by Aylin67** [comment]
19% falto bibliografia,imagenes..........

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
